# Generated by Django 5.1.2 on 2025-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_item_price_alter_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=256)),
                ('Another', models.IntegerField()),
                ('One', models.IntegerField()),
            ],
        ),
    ]
